services:
  flibusta-tg-bot:
    container_name: flibusta-tg-bot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./flibusta_bot:/app/flibusta_bot
      - ./migrations:/app/migrations
      - ./alembic.ini:/app/alembic.ini
    ports:
      - "9998:8000"
    sysctls:
      net.core.somaxconn: 65536
    networks:
      - flibusta-tg-bot-network

networks:
  flibusta-tg-bot-network:
    driver: bridge
