"""add additional data to books model

Revision ID: 145c81a5c874
Revises: 23ed01f48d53
Create Date: 2025-05-31 20:13:12.958319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '145c81a5c874'
down_revision: Union[str, None] = '23ed01f48d53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('downlad_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('books', sa.Column('hashtags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'hashtags')
    op.drop_column('books', 'downlad_urls')
    # ### end Alembic commands ###
