"""remove books.lebrary_id

Revision ID: 23ed01f48d53
Revises: bc28439775de
Create Date: 2025-05-31 19:56:48.381817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23ed01f48d53'
down_revision: Union[str, None] = 'bc28439775de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'library_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('library_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
